# Data setting
dataset:
  data_name : wn18

graph_obj:
  batch_size : 50000
  split_size : 0.5
  neg_sampling : 5
  edge_sampler : uniform


# Net setting
model:
  dropout : 0.2
  n_hidden : 500
  n_layers : 2
  num_class : 18

optimizer:
  lr : 0.01
  regularization : 0.01
  grad_norm : 1.0


# Training setting
train:
  seed: 2020
  gpu : 0
  n_epochs : 1000
  folder : checkpoint
  verbose : True
